version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ecashbook_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rey002
      MYSQL_DATABASE: e_cashbook_db
    ports:
      - "3306:3306"